---
- hosts: all
  user: mimmy
  sudo: yes
  vars:
    mysql_root_password: pass
  tasks:
    - include: tasks/mysql.yml
    - include: tasks/nginx.yml
    - include: tasks/ruby.yml
    - include: tasks/app_base.yml
