---
- hosts: all
  sudo: yes
  vars_files:
    - vars/omni_server.yml
  tasks:
    - include: tasks/mysql.yml
    - include: tasks/nginx.yml
    - include: tasks/ruby.yml
    - include: tasks/app_base.yml
